image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_PROFILE: "test"
  APIGEE_DEPLOYMENT_SUFFIX: ""
  APIGEE_ORG: "emea-demo7"
  GIT_BRANCH: "main"
  AUTHOR_EMAIL: "clalevee@gmail.com"
  TEST_HOST: "$APIGEE_ORG-$MAVEN_PROFILE.apigee.net"
  # APIGEE_CREDS_USR & APIGEE_CREDS_PSW are stored in CI/CD variable settings

cache:
  paths:
    - .m2/repository/
    - target/
    - node_modules/

stages:
  - install-dependencies
  - static-code-analysis
  - unit-test
  - mvn-package
  - mvn-config
  - mvn-deploy
  - test-integration


install-dependencies:
  stage: install-dependencies
  image: node:12-alpine 
  script:
    - npm install --silent --no-fund

apigeelint:
  stage: static-code-analysis
  image: node:12-alpine 
  script:
    - ./node_modules/apigeelint/cli.js -s ./apiproxy -f html.js -e PO013 > ./target/apigeelint-out.html
  artifacts:
    paths:
    - ./target/apigeelint-out.html
    expire_in: 30 minute
  only:
    - master


eslint:
  stage: static-code-analysis
  image: node:12-alpine 
  script:
      - ./node_modules/eslint/bin/eslint.js -c ./.eslintrc-jsc.yml --format html ./apiproxy/resources/jsc > ./target/eslint-out.html
  artifacts:
    paths:
    - ./target/eslint-out.html
  only:
    - master

mocha:
  stage: unit-test
  image: node:12-alpine 
  script:
    - ./node_modules/nyc/bin/nyc.js --reporter=html --reporter=text ./node_modules/mocha/bin/_mocha ./test/unit
  artifacts:
    paths:
    - ./coverage/index.html
  only:
    - master

mvn-package:
  stage: mvn-package
  script:
    - mvn process-resources -P$MAVEN_PROFILE -Dcommit=$GIT_COMMIT -Dbranch=$GIT_BRANCH -Dauthor=$AUTHOR_EMAIL -Ddeployment.suffix=$APIGEE_DEPLOYMENT_SUFFIX

mvn-config:
  stage: mvn-config
  script:
    - mvn apigee-enterprise:configure -P$MAVEN_PROFILE -Ddeployment.suffix=$APIGEE_DEPLOYMENT_SUFFIX 
    
mvn-deploy-config:
  stage: mvn-deploy
  script:
    - mvn install -P$MAVEN_PROFILE -Dapigee.org=$APIGEE_ORG -Dapigee.username=$APIGEE_CREDS_USR -Dapigee.password=$APIGEE_CREDS_PSW -Dapigee.config.file=./EdgeConfig/edge.json -Dapigee.config.options=update

mvn-deploy-proxy:
  stage: mvn-deploy
  script:
    - mvn apigee-enterprise:deploy -P$MAVEN_PROFILE -Dapigee.org=$APIGEE_ORG -Dapigee.username=$APIGEE_CREDS_USR -Dapigee.password=$APIGEE_CREDS_PSW -Ddeployment.suffix=$APIGEE_DEPLOYMENT_SUFFIX

test-integration:
  stage: test-integration
  image: node:12-alpine 
  script:
    - sed -i "s/organization_hostname/$TEST_HOST/g" ./target/test/integration/features/support/init.js
    - node ./node_modules/cucumber/bin/cucumber-js ./target/test/integration --format json:./reports.json
    - node ./test/integration/index.js
  artifacts:
    paths:
    - ./cucumber_report.html
    expire_in: 30 minute
