image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_PROFILE: "test"
  APIGEE_DEPLOYMENT_SUFFIX: ""
  APIGEE_ORG: "emea-demo7"
  GIT_BRANCH: "main"
  AUTHOR_EMAIL: "clalevee@gmail.com"
  # APIGEE_CREDS_USR & APIGEE_CREDS_PSW are stored in CI/CD variable settings

cache:
  paths:
    - .m2/repository/
    - target/
    - node_modules/

stages:
  - install-dependencies
  - static-code-analysis
  - mvn-package
  - mvn-config
  - mvn-deploy
  - test-integration

install-dependencies:
  stage: install-dependencies
  image: node:12-alpine 
  script:
    - npm install --silent --no-fund

static-code-analysis:
  stage: static-code-analysis
  image: node:12-alpine 
  script:
    #- npm install -g apigeelint
    - ./node_modules/apigeelint/cli.js -s ./apiproxy -f html.js -e PO013 > ./target/apigeelint-out.html
  artifacts:
    paths:
    - ./target/apigeelint-out.html
    expire_in: 30 minute


mvn-package:
  stage: mvn-package
  script:
    - mvn process-resources -P$MAVEN_PROFILE -Dcommit=$GIT_COMMIT -Dbranch=$GIT_BRANCH -Dauthor=$AUTHOR_EMAIL -Ddeployment.suffix=$APIGEE_DEPLOYMENT_SUFFIX

mvn-config:
  stage: mvn-config
  script:
    - mvn apigee-enterprise:configure -P$MAVEN_PROFILE -Ddeployment.suffix=$APIGEE_DEPLOYMENT_SUFFIX

mvn-deploy:
  stage: mvn-deploy
  script:
    - mvn apigee-enterprise:deploy -P$MAVEN_PROFILE -Dapigee.org=$APIGEE_ORG -Dapigee.username=$APIGEE_CREDS_USR -Dapigee.password=$APIGEE_CREDS_PSW -Ddeployment.suffix=$APIGEE_DEPLOYMENT_SUFFIX

test-integration:
  stage: test-integration
  image: node:12-alpine 
  script:
    - node ./node_modules/cucumber/bin/cucumber-js ./target/test/integration --format json:./target/reports.json
  artifacts:
    paths:
    - ./target/reports.json
    expire_in: 30 minute