image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_PROFILE: "test"
  APIGEE_DEPLOYMENT_SUFFIX: ""
  APIGEE_ORG: "emea-demo7"
  GIT_BRANCH: "main"
  AUTHOR_EMAIL: "clalevee@gmail.com"
  # APIGEE_CREDS_USR & APIGEE_CREDS_PSW are stored in CI/CD variable settings

cache:
  paths:
    - .m2/repository/
    - target/

package:
  stage: package
  script:
    - mvn process-resources -P$MAVEN_PROFILE -Dcommit=$GIT_COMMIT -Dbranch=$GIT_BRANCH -Dauthor=$AUTHOR_EMAIL -Ddeployment.suffix=$APIGEE_DEPLOYMENT_SUFFIX

config:
  stage: config
  script:
    - mvn apigee-enterprise:configure -P$MAVEN_PROFILE -Ddeployment.suffix=$APIGEE_DEPLOYMENT_SUFFIX

deploy:
  stage: deploy
  script:
    - mvn apigee-enterprise:deploy -P$MAVEN_PROFILE -Dapigee.org=$APIGEE_ORG -Dapigee.username=$APIGEE_CREDS_USR -Dapigee.password=$APIGEE_CREDS_PSW -Ddeployment.suffix=$APIGEE_DEPLOYMENT_SUFFIX
