image: maven:latest

variables:
  DEFAULT_APIGEE_ORG: "emea-demo7"
  DEFAULT_APIGEE_ENV: "test"
  #TEST_HOST: x-demo7.lalevee.org
  TEST_HOST: "$DEFAULT_APIGEE_ORG-$DEFAULT_APIGEE_ENV.apigee.net"



  #API_VERSION: "googleapi" 
  # or 
  API_VERSION: "apigeeapi"

  # GCP_SERVICE_ACCCOUNT, APIGEE_CREDS_USR & APIGEE_CREDS_PSW are stored in GitLab CI/CD variable settings
  # GCP_SERVICE_ACCCOUNT variable, type "File" 

cache:
  paths:
    - .m2/repository/
    - target/
    - node_modules/


before_script: 
  - |

      # Main branch for Apigee test environment
      if [ $CI_COMMIT_BRANCH == "main" ]; then
            APIGEE_DEPLOYMENT_SUFFIX=""
            APIGEE_ENV="$DEFAULT_APIGEE_ENV"
            APIGEE_ORG="$DEFAULT_APIGEE_ORG"

        # Prod branch for Apigee prod environment
        else
          if [ $CI_COMMIT_BRANCH == "prod" ]; then
            APIGEE_DEPLOYMENT_SUFFIX=""
            APIGEE_ENV="prod"
            APIGEE_ORG="$DEFAULT_APIGEE_ORG"

          # All other branches are deployed as separate proxies with suffix in the test environment
          else
            APIGEE_DEPLOYMENT_SUFFIX=${CI_COMMIT_BRANCH// /-} 
            APIGEE_ENV="$DEFAULT_APIGEE_ENV"
            APIGEE_ORG="$DEFAULT_APIGEE_ORG"
          fi
        fi



stages:
  - install-dependencies
  - static-code-analysis
  - unit-test
  - mvn-deploy-config
  - mvn-package
  - mvn-config
  - mvn-deploy-proxy
  - test-integration


# install-dependencies
install-dependencies:
  stage: install-dependencies
  image: node:12-alpine 
  script:
    - npm install --silent --no-fund



# Static code analysis (Proxy, JS): static-code-analysis
apigeelint:
  stage: static-code-analysis
  image: node:12-alpine 
  script:
    - ./node_modules/apigeelint/cli.js -s ./apiproxy -f html.js -e PO013 > ./apigeelint-out.html
  artifacts:
    paths:
    - ./apigeelint-out.html

eslint:
  stage: static-code-analysis
  image: node:12-alpine 
  script:
      - ./node_modules/eslint/bin/eslint.js -c ./.eslintrc-jsc.yml --format html ./apiproxy/resources/jsc > ./eslint-out.html
  artifacts:
    paths:
    - ./eslint-out.html

mocha:
  stage: unit-test
  image: node:12-alpine 
  script:
    - ./node_modules/nyc/bin/nyc.js --reporter=html --reporter=text ./node_modules/mocha/bin/_mocha ./test/unit
  artifacts:
    paths:
    - ./coverage/index.html


  
  
# Deploy config (KVM, target servers, etc.): mvn-deploy-config
mvn-deploy-config-edge:
  stage: mvn-deploy-config
  script:
    - sed -i "s/target_apigee_env/$APIGEE_ENV/g" ./EdgeConfig/edge.json
    - mvn install -Papigeeapi -Dapigee.org=$APIGEE_ORG -Denv=$APIGEE_ENV -Dapigee.username=$APIGEE_CREDS_USR -Dapigee.password=$APIGEE_CREDS_PSW -Dapigee.config.file=./EdgeConfig/edge.json -Dapigee.config.options=update
  rules:
    - if: $API_VERSION == "apigeeapi"

mvn-deploy-config-xhybrid:
  stage: mvn-deploy-config
  script:
    - sed -i "s/target_apigee_env/$APIGEE_ENV/g" ./EdgeConfig/edge.json
    - mvn install -Pgoogleapi -Dapigee.org=$APIGEE_ORG -Denv=$APIGEE_ENV -Dsa=$GCP_SERVICE_ACCCOUNT -Dapigee.config.file=./EdgeConfig/edge.json -Dapigee.config.options=update
  rules:
    - if: $API_VERSION == "googleapi"  



# Deploy Proxy: mvn-package, mvn-config, mvn-deploy-proxy
mvn-package:
  stage: mvn-package
  script:
    - if [ "$AUTHOR_EMAIL" == "" ]; then AUTHOR_EMAIL="$GITLAB_USER_EMAIL"; fi
    - mvn process-resources -P$API_VERSION -Dcommit=$GIT_COMMIT -Dbranch=$GIT_BRANCH -Dauthor=$AUTHOR_EMAIL -Ddeployment.suffix=$APIGEE_DEPLOYMENT_SUFFIX

mvn-config:
  stage: mvn-config
  script:
    - mvn apigee-enterprise:configure -P$API_VERSION -Dorg=$APIGEE_ORG -Denv=$APIGEE_ENV  -Ddeployment.suffix=$APIGEE_DEPLOYMENT_SUFFIX 

mvn-deploy-proxy-xhybrid:
  stage: mvn-deploy-proxy
  script:
    - mvn apigee-enterprise:deploy -Pgoogleapi -Denv=$APIGEE_ENV -Dsa=$GCP_SERVICE_ACCCOUNT -Dorg=$APIGEE_ORG -Ddeployment.suffix=$APIGEE_BUILD_DEPLOYMENT_SUFFIX 
  rules:
    - if: $API_VERSION == "googleapi"

mvn-deploy-proxy-edge:
  stage: mvn-deploy-proxy
  script:
      - mvn apigee-enterprise:deploy -Papigeeapi -Dorg=$APIGEE_ORG -Denv=$APIGEE_ENV -Dpassword=$APIGEE_CREDS_PSW -Dusername=$APIGEE_CREDS_USR -Ddeployment.suffix=$APIGEE_BUILD_DEPLOYMENT_SUFFIX 
  rules:
    - if: $API_VERSION == "apigeeapi"



# Integration test: test-integration
apickli:
  stage: test-integration
  image: node:12-alpine 
  script:
    - sed -i "s/organization_hostname/$TEST_HOST/g" ./test/integration/features/support/init.js
    - node ./node_modules/cucumber/bin/cucumber-js ./test/integration --format json:./report.json
    - node ./test/integration/index.js
  artifacts:
    paths:
    - ./cucumber_report.html


