image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DEFAULT_APIGEE_ORG: "xxxxxx"
  # APIGEE_CREDS_USR & APIGEE_CREDS_PSW are stored in GitLab CI/CD variable settings

cache:
  paths:
    - .m2/repository/
    - target/
    - node_modules/

before_script: 
  - |

      # Main branch for Apigee test environment
      if [ $CI_COMMIT_BRANCH == "main" ]; then
            APIGEE_DEPLOYMENT_SUFFIX=""
            MAVEN_PROFILE="test"
            APIGEE_ORG="$DEFAULT_APIGEE_ORG"

        # Prod branch for Apigee prod environment
        else
          if [ $CI_COMMIT_BRANCH == "prod" ]; then
            APIGEE_DEPLOYMENT_SUFFIX=""
            MAVEN_PROFILE="prod"
            APIGEE_ORG="$DEFAULT_APIGEE_ORG"

          # All other branches are deployed as separate proxies with suffix in the test environment
          else
            APIGEE_DEPLOYMENT_SUFFIX=${CI_COMMIT_BRANCH// /-} 
            MAVEN_PROFILE="test"
            APIGEE_ORG="$DEFAULT_APIGEE_ORG"
          fi
        fi
        TEST_HOST="$APIGEE_ORG-$MAVEN_PROFILE.apigee.net"


stages:
  - install-dependencies
  - static-code-analysis
  - unit-test
  - mvn-package
  - mvn-config
  - mvn-deploy
  - test-integration


install-dependencies:
  stage: install-dependencies
  image: node:12-alpine 
  script:
    - npm install --silent --no-fund


apigeelint:
  stage: static-code-analysis
  image: node:12-alpine 
  script:
    - ./node_modules/apigeelint/cli.js -s ./apiproxy -f html.js -e PO013 > ./apigeelint-out.html
  artifacts:
    paths:
    - ./apigeelint-out.html
    expire_in: 30 minute


eslint:
  stage: static-code-analysis
  image: node:12-alpine 
  script:
      - ./node_modules/eslint/bin/eslint.js -c ./.eslintrc-jsc.yml --format html ./apiproxy/resources/jsc > ./eslint-out.html
  artifacts:
    paths:
    - ./eslint-out.html


mocha:
  stage: unit-test
  image: node:12-alpine 
  script:
    - ./node_modules/nyc/bin/nyc.js --reporter=html --reporter=text ./node_modules/mocha/bin/_mocha ./test/unit
  artifacts:
    paths:
    - ./coverage/index.html


mvn-package:
  stage: mvn-package
  script:
    - if [ "$AUTHOR_EMAIL" == "" ]; then AUTHOR_EMAIL="$GITLAB_USER_EMAIL"; fi
    - mvn process-resources -P$MAVEN_PROFILE -Dcommit=$GIT_COMMIT -Dbranch=$GIT_BRANCH -Dauthor=$AUTHOR_EMAIL -Ddeployment.suffix=$APIGEE_DEPLOYMENT_SUFFIX

mvn-config:
  stage: mvn-config
  script:
    - mvn apigee-enterprise:configure -P$MAVEN_PROFILE -Ddeployment.suffix=$APIGEE_DEPLOYMENT_SUFFIX 

mvn-deploy-config:
  stage: mvn-deploy
  script:
    - sed -i "s/target_apigee_env/$MAVEN_PROFILE/g" ./EdgeConfig/edge.json
    - mvn install -P$MAVEN_PROFILE -Dapigee.org=$APIGEE_ORG -Dapigee.username=$APIGEE_CREDS_USR -Dapigee.password=$APIGEE_CREDS_PSW -Dapigee.config.file=./EdgeConfig/edge.json -Dapigee.config.options=update

mvn-deploy-proxy:
  stage: mvn-deploy
  script:
    - mvn apigee-enterprise:deploy -P$MAVEN_PROFILE -Dapigee.org=$APIGEE_ORG -Dapigee.username=$APIGEE_CREDS_USR -Dapigee.password=$APIGEE_CREDS_PSW -Ddeployment.suffix=$APIGEE_DEPLOYMENT_SUFFI

apickli:
  stage: test-integration
  image: node:12-alpine 
  script:
    - sed -i "s/organization_hostname/$TEST_HOST/g" ./test/integration/features/support/init.js
    - node ./node_modules/cucumber/bin/cucumber-js ./test/integration --format json:./report.json
    - node ./test/integration/index.js
  artifacts:
    paths:
    - ./cucumber_report.html
    expire_in: 30 minute
